spring:
  # jpa config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    hikari:
      maximum-pool-size: 1

  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
